# Generated by Django 4.0.2 on 2022-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # primary(기본키) : 레코드들을 구별 해 주는 유일한 값, 테이블 당 하나만 가지고 있어야 한다!
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
