# Generated by Django 4.0.2 on 2022-04-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
